export { default as HeroSection } from './HeroSection'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as Footer } from './Footer'
export { default as FeaturesSection } from './FeaturesSection'
export { default as TemplateGallery } from './TemplateGallery'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as FAQSection } from './FAQSection'
export { default as ContactSection } from './ContactSection'